[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200

; 1. สั่งให้ VS Code โหลด Library อัตโนมัติ
lib_deps =
  bodmer/TFT_eSPI@^2.5.31
  bodmer/TJpg_Decoder@^1.1.0

; 2. ตั้งค่าขาหน้าจอ TFT (แทนการเข้าไปแก้ไฟล์ User_Setup.h)
build_flags =
  -D USER_SETUP_LOADED=1
  -D ST7735_DRIVER=1
  -D TFT_WIDTH=128
  -D TFT_HEIGHT=160
  -D ST7735_REDTAB=1
  -D TFT_MISO=-1
  -D TFT_MOSI=15
  -D TFT_SCLK=14
  -D TFT_CS=13
  -D TFT_DC=12
  -D TFT_RST=-1
  -D LOAD_GLCD=1
  -D SPI_FREQUENCY=27000000